# Boolean Indexing



In [1]:
import numpy as np

First, we'll create an array that we'll be indexing.

In [9]:
x = np.array([[1, 0, 9], [3, 4, 1], [2, 4, 1], [3, 10, 1]])
print(x)

[[ 1  0  9]
 [ 3  4  1]
 [ 2  4  1]
 [ 3 10  1]]


Now, let's grab all values greater than 5. First, we create a Boolean array that has True when the corresponding entry in x is greater than 5, False otherwise.

In [8]:
boolean_array = x > 5

print(boolean_array)

[[False False  True]
 [False False False]
 [False False False]
 [False  True False]]


Next, we can index into x using that array and we get back all the entries in x where the corresponding entry in the boolean array is True

In [10]:
x[boolean_array]

array([ 9, 10])

Note that we lose any structure in terms of where those entries occurred

We can also use Boolean indexing to get specific rows if we have a Boolean array that is the length of the number of rows that consists of Trues and Falses.

Let's get the rows in x where the mean of the row is over 3.

First, we can get the mean per row, then we can compare to 3 to get a boolean array.

In [13]:
mean_per_row = np.mean(x, axis=1)

boolean_array = mean_per_row > 3

print(boolean_array)

[ True False False  True]


Now we can use that to index into the rows.

In [14]:
x[boolean_array, :]

array([[ 1,  0,  9],
       [ 3, 10,  1]])

We can also do the same with columns.

Below, we return columns that had mean greater than 3

In [17]:
boolean_array = np.mean(x, axis=0)>3

x[:, boolean_array]

array([[ 0],
       [ 4],
       [ 4],
       [10]])