# Indexing

In [ ]:
import numpy as np

Let's first create this array

![picture](https://raw.githubusercontent.com/ebatty/CodingBootcamp/master/images/array.png)

In [ ]:
x = np.array([[4, 2, 1, 3], [1, 0, 3, 5], [6, 7, 8, 2]])

We can grab specific data points using:

`x[row index, column index]`

In [ ]:
x[2, 1]

7

We can grab multiple column values in one row with:
```
x[row index, start index:stop index*]
```

\* not inclusive of stop index

In [ ]:
x[0, 1:3]

array([2, 1])

We can skip over certain rows/columns with a step count:

`x[row index, start index:stop index:step count]`

will get columns from start index up to but not including stop index, skipping every step count.

In other words, x[0, 0:4:2] would get every second column from column with index 0 to column with index 4 (so columns 0 and 2).

We can overwrite subsets of our array.

In [ ]:
x[0, 0] = 100

In [ ]:
x

array([[100,   2,   1,   3],
       [  1,   0,   3,   5],
       [  6,   7,   8,   2]])

In [ ]:
x[0, :] = 100

In [ ]:
x

array([[100, 100, 100, 100],
       [  1,   0,   3,   5],
       [  6,   7,   8,   2]])